spring:
  profiles: default

datasource:
  ams:
    initialize: true
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/test"
    user-name: "postgres"
    password: "daisy!"
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000